name: docker-github
on:
  workflow_dispatch

jobs:
  deploy_to_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - kinesis
          - kafka
        include:
          - suffix: ""
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Docker:stage
        run: sbt "project ${{ matrix.platform }}" docker:stage
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.platform }}/target/docker/stage
          file: ${{ matrix.platform }}/target/docker/stage/Dockerfile
          tags: ghcr.io/${{ github.repository }}/opensnowcat-collector-${{ matrix.platform }}:latest
          push: true